name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    #Stopped working on 05/07/2024:
    #- name: Build the site in the jekyll/builder container
    #  run: |
    #    docker run \
    #    -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #    jekyll/builder:3.8 /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    #
    # following recipe from https://github.com/gallomassimo/gallomassimo.github.io/blob/source/.github/workflows/build.yml
    - name: Set up Ruby 2.6 # Does not work with Ruby 3.2 (jekyll scholar uses exists)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        gem install bundler -v 2.4.22
        bundle install
        bundle exec jekyll build
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
